app_sisponto/app/talks/forms.py
from flask_wtf import Form, FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, DateField
from wtforms.validators import Optional, Length, Required, DataRequired, URL


class ProfileForm(FlaskForm):
    name = StringField('Name', validators=[Optional(), Length(1, 64)])
    location = StringField('Location', validators=[Optional(), Length(1, 64)])
    bio = TextAreaField('Bio')
    submit = SubmitField('Submit')

class TalkForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(1, 128)])
    description = TextAreaField('Description')
    slides = StringField('Slides Embed Code (450 pixels wide)')
    video = StringField('Video Embed Code (450 pixels wide)')
    venue = StringField('Venue',
                        validators=[DataRequired(), Length(1, 128)])
    venue_url = StringField('Venue URL',
                            validators=[Optional(), Length(1, 128), URL()])
    date = DateField('Date')
    submit = SubmitField('Submit')

    def from_model(self, talk):
        self.title.data = talk.title
        self.description.data = talk.description
        self.slides.data = talk.slides
        self.video.data = talk.video
        self.venue.data = talk.venue
        self.venue_url.data = talk.venue_url
        self.date.data = talk.date

    def to_model(self, talk):
        talk.title = self.title.data
        talk.description = self.description.data
        talk.slides = self.slides.data
        talk.video = self.video.data
        talk.venue = self.venue.data
        talk.venue_url = self.venue_url.data
        talk.date = self.date.data

app_sisponto/app/talks/__init__.py
from flask import Blueprint
talks = Blueprint('talks', __name__)
from . import routes

app_sisponto/app/talks/routes.py
from flask import render_template, flash, redirect, url_for
from flask_login import login_required, current_user

from app import db
from app.auth.forms import ProfileForm
from app.talks.forms import TalkForm
from . import talks
from ..models import User, Talk


@talks.route('/')
def index():
    talk_list = Talk.query.order_by(Talk.date.desc()).all()
    return render_template('talks/index.html', talks=talk_list)

@talks.route('/user/<username>')
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    talk_list = user.talks.order_by(Talk.date.desc()).all()
    return render_template('talks/user.html', user=user, talks = talk_list)

@talks.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    form = ProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.location = form.location.data
        current_user.bio = form.bio.data
        db.session.add(current_user._get_current_object())
        db.session.commit()
        flash('Your profile has been updated.')
        return redirect(url_for('talks.user', username=current_user.username))
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.bio.data = current_user.bio
    return render_template('talks/profile.html', form=form)

@talks.route('/new', methods=['GET', 'POST'])
@login_required
def new_talk():
    form = TalkForm()
    if form.validate_on_submit():
        talk = Talk(author=current_user)
        form.to_model(talk)
        db.session.add(talk)
        db.session.commit()
        flash('The talk was added successfully.')
        return redirect(url_for('.index'))
    return render_template('talks/edit_talk.html', form=form)

@talks.route('/talk/<int:id>', methods=['GET', 'POST'])
def talk(id):
    talk = Talk.query.get_or_404(id)
    headers = {}
    if current_user.is_authenticated:
        headers['X-XSS-Protection'] = '0'
    return render_template('talks/talk.html', talk=talk),\
           200, headers

app_sisponto/app/templates/talks/_talk_header.html
<div class="talk-header">
    {% if talk.user == current_user %}
    <a class="btn btn-primary pull-right" href="{{ url_for('talks.edit_talk', id=talk.id) }}">Edit</a>
    {% elif current_user.is_admin %}
    <a class="btn btn-danger pull-right" href="{{ url_for('talks.edit_talk', id=talk.id) }}">Edit</a>
    {% endif %}
    <h2><a href="{{ url_for('talks.talk', id=talk.id) }}">{{ talk.title }}</a></h2>
    <h3>{{ talk.description }}</h3>
    <p>
        Presented by <a href="{{ url_for('talks.user', username=talk.author.username) }}">{{ talk.author.username }}</a> at
        {% if talk.venue_url %}
            <a href="{{ talk.venue_url }}">{{ talk.venue }}</a>
        {% else %}
            {{ talk.venue }}
        {% endif %}
        on {{ talk.date }}.
    </p>
</div>

app_sisponto/app/templates/talks/_talks.html
<ul class="talk-list">
{% for talk in talks %}
    <li class="talk">
    {% include "talks/_talk_header.html" %}
    </li>
{% endfor %}
</ul>

app_sisponto/app/templates/talks/edit_talk.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="page-header">
    <h1>Talk</h1>
</div>
{{ wtf.quick_form(form) }}
{% endblock %}

app_sisponto/app/templates/talks/index.html
{% extends "base.html" %}
{% block page_content %}
    {% if current_user.is_authenticated %}
        <h1>Hello {{ current_user.username }}!</h1>
    {% endif %}
    {% if not current_user.is_authenticated %}
        <h1>SISPONTO</h1>
    {% endif %}
    {% include "talks/_talks.html" %}
{% endblock %}

app_sisponto/app/templates/talks/profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="page-header">
    <h1>Edit Profile</h1>
</div>
{{ wtf.quick_form(form) }}
{% endblock %}

app_sisponto/app/templates/talks/talk.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="page-header">
    {% include "talks/_talk_header.html" %}
</div>
<div class="talk-body">
    {% if talk.video %}
    <div class="talk-video">
    {{ talk.video | safe }}
    </div>
    {% endif %}
    {% if talk.slides %}
    <div class="talk-slides">
    {{ talk.slides | safe }}
    </div>
    {% endif %}
</div>
{% if comments %}
<h3 id="comments">Comments</h3>
{% include "talks/_comments.html" %}
<ul class="pager">
    {% if pagination.has_prev %}
    <li class="previous"><a href="{{ url_for('talks.talk', id=talk.id, page=pagination.prev_num) }}#comments">&larr; Older</a></li>
    {% else %}
    <li class="previous disabled"><a href="#">&larr; Older</a></li>
    {% endif %}
    {% if pagination.has_next %}
    <li class="next"><a href="{{ url_for('talks.talk', id=talk.id, page=pagination.next_num) }}#comments">Newer &rarr;</a></li>
    {% else %}
    <li class="next disabled"><a href="#">Newer &rarr;</a></li>
    {% endif %}
</ul>
{% endif %}
{% endblock %}

{% block scripts %}
{{ super() }}
<script src="http://cdnjs.cloudflare.com/ajax/libs/autosize.js/1.18.1/jquery.autosize.min.js"></script>
<script>
    $(document).ready(function() {
        $('#flask-pagedown-body').autosize();
    });
</script>
{% endblock %}

app_sisponto/app/templates/talks/user.html
{% extends "base.html" %}
{% block page_content %}
    <div class="page-header user-profile">
        <div class="user-avatar"><img src="{{ user.gravatar(128) }}" /></div>
        <h1>{{ user.username }}</h1>
    </div>
    {% include "talks/_talks.html" %}
{% endblock %}